spring:
  application:
     name: ${APPLICATION_NAME:payment-servicee}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/{MYSQL_DB:payments}?createDatabaseIfNotExist=true
    username: ${USERNAME:root}
    password: ${PASSWORD:mysql}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:9092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    producer:
      bootstrap-servers:
        - "localhost:9092"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${SERVER_PORT:9090}
eureka:
  client:
     register-with-eureka: ${REGISTER_WITH_EUREKA:true}
     fetch-registry: ${FETCH_REGISTRY:true}
     serviceurl:
         defaultZone:
            http://localhost:8761/eureka

stripe:
  key: sk_test_51PF8ExSC93b1n3DmUSI4ODTkoypA4hKkeWvfPHrWs8TcXm0xMtNxSDXSUEpraXVAD3mfRMyTgNXiNrgD5Qfd0lfo0080Lbbkbv