spring:
  application:

    name: ${APPLICATION_NAME:booking-service}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/{MYSQL_DB:bookings}?createDatabaseIfNotExist=true
    username: ${USERNAME:root}
    password: ${PASSWORD:mysql}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:9091}
eureka:
  client:
     register-with-eureka: ${REGISTER_WITH_EUREKA:true}
     eureka.client.fetch-registry: ${FETCH_REGISTRY:true}
  serviceurl:
     defaultZone=http://localhost:8761/eureka
